### ISSUE TITLE
fn_ProofPoint_trap URL concatenation results in an incorrect url

### ISSUE THREAD

**Issue by JasonMKane** [ibmresilient/resilient-community-apps#48]
https://github.com/ibmresilient/resilient-community-apps/blob/8f4ffdebb5f0f5bf180ee22858b47bfaf681423b/fn_proofpoint_trap/fn_proofpoint_trap/lib/pptr_client.py#L142

The use of the urljoin function results in an incomplete URL at runtime.  Using the example value for base_url in the README.md for fn_proofpoint_trap: https://192.168.1.1/api.  Passing this through URL join will take remove the /api from the base_url in the app.config, and concatenate the route resulting in:
https://192.168.1.1/incidents/123456.json (Bad Url) instead of
https://192.168.1.1/api/incidents/123456.json 

The resulting URL to the incident resource is incorrect.

EDIT: Removed failed attempt at markdown to highlight the missing /api in the URL.

**Comment by breid1313** [comment]
Are you still having this issue? It looks like this was actually fixed in version 1.0.1, so if you upgrade via the App Exchange the integration should work.

**Comment by JasonMKane** [comment]
No we're no longer having this issue.  I can confirm it was corrected in 1.0.1.
