### ISSUE TITLE
I need an example to use the "utilities_call_rest_api".

### ISSUE THREAD

**Issue by jdelcol** [ibmresilient/resilient-community-apps#5]
I see the parameters, but I do not know what to put in each of them.

Is it possible to use a wsdl?

**Comment by hpyle** [comment]
The parameters are:
* rest_method: this is the HTTP method used to call the API, one of GET, PUT, POST, etc.
* rest_url: the URL that will be called.
* rest_headers: a textarea that can contain any HTTP headers needed.
* rest_body: for HTTP POST requests, this is the body (text, JSON or XML, for example).
* rest_verify: if "false", the TLS certificate from the server will not be verified.

This function is for direct HTTP calls, e.g. for REST/JSON APIs.  It does not use WSDL.
