### ISSUE TITLE
bug in fn_virustotal

### ISSUE THREAD

**Issue by PyiPai** [ibmresilient/resilient-community-apps#50]
## Describe How to Reproduce

fn_virustotal/fn_virustotal/components/virustotal.py

/fn_virustotal/fn_virustotal/components/virustotal.py", line 178, in check_results
    if int(curr_time - start_time)/1000 >= int(self.options('max_polling_wait_sec')):
TypeError: 'dict' object is not callable

This linke 178 should be changed to if int(curr_time - start_time)/1000 >= int(self.options['max_polling_wait_sec'])
Notice the square brackets instead of the round brackets.

**Comment by JOHNQUIR** [comment]
Please update with version of virus total ...

**Comment by breid1313** [comment]
Hi @PyiPai. Thanks for bringing this up! We addressed this in the current version of fn_virustotal. Upgrade the integration and your issue should be resolved.
